{
	"version": 1548235723,
	"fileList": [
		"data.js",
		"c2runtime.js",
		"jquery-2.1.1.min.js",
		"offlineClient.js",
		"images/player-sheet0.png",
		"images/enemy1-sheet0.png",
		"images/enemy2-sheet0.png",
		"images/enemy22-sheet0.png",
		"images/bullet-sheet0.png",
		"images/boss1-sheet0.png",
		"images/bulleten-sheet0.png",
		"images/bulleten1-sheet0.png",
		"images/bg1.png",
		"images/buttonstart2-sheet0.png",
		"images/exit2-sheet0.png",
		"images/navigasi.png",
		"images/metalpanel-sheet0.png",
		"images/home-sheet0.png",
		"images/next-sheet0.png",
		"images/return-sheet0.png",
		"images/bg3.png",
		"images/enemy3-sheet0.png",
		"images/sprite2-sheet0.png",
		"images/sprite-sheet0.png",
		"images/bullet3-sheet0.png",
		"images/boss2-sheet0.png",
		"images/bg2.png",
		"images/boss3-sheet0.png",
		"media/laser1.ogg",
		"media/laser9.ogg",
		"media/menu.ogg",
		"media/stage 1.ogg",
		"media/stage 2.ogg",
		"media/stage 3.ogg",
		"icon-16.png",
		"icon-32.png",
		"icon-114.png",
		"icon-128.png",
		"icon-256.png",
		"loading-logo.png"
	]
}